### ISSUE TITLE
palworld-server

### ISSUE THREAD

**Issue by arpd** [gradientvera/GradientOS#3]
Hi, I tried copying your palworld and `steamcmd` nix files; I had a problem where palworld server was trying to create `Pal/Saved` in `/var/lib/steamcmd/steam-app-...`, but the application runs as the user `palworld` so it does not have permission to do anything in the directories owned by `steamcmd`. I made it manually and set `a+rwx` on the directory, . Now the server starts, occupies 15% cpu and ~1GiB ram, which makes me think that it isn't actually starting a 'world' or whatever.. It's populated the save directory with some stuff; I can see that the port is bound with `netstat -tulpn`, but I cannot connect and the steady memory and cpu utilisation makes me think something isn't working quite right.

Are there any other things you had to do to get it to run?

**Comment by gradientvera** [comment]
There was a problem with permissions which I had to fix manually with chmod, I pushed a commit so that it works out of the box without any manual steps.
Also see this fediverse thread for more info: https://hachyderm.io/@jakehamilton/111805056049399660
